### ISSUE TITLE
[LSTs] Handling additive tokens

### ISSUE THREAD

**Issue by MaxMustermann2** [ExocoreNetwork/exocore-contracts#60]
Parts of this issue apply to [ExocoreNetwork/exocore](https://github.com/ExocoreNetwork/exocore) as well.

`stETH`, Lido's staked Ether, is an additive token. This means that staking rewards accrue as additional `stETH` balance and the value of `stETH` to `ETH` is always `1:1`. Our system is not designed with this in mind. Fortunately, Lido had the foresight for this and came up with `wstETH` which is a compounding wrapped version of `stETH`. We can use this token directly instead of using `stETH` and offer a wrapping link / mechanism in the UI.

The only other additive token that I see is Origin Staked Ether while others are compounding.

**Comment by adu-web3** [comment]
nice catch! This is an important point we should take care of. Maybe we should document in `ClientChainGateway.sol` or `LSTRestakingController.sol` to notice that these contracts only work with LST tokens that are compounding tokens(price fluctuates while balance remain not changed) instead of rebasable tokens(balance fluctuates while price remains not changed)
